// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd9Zn_PSuEIUfviA0VVb67fK0YkthR4BI',
    appId: '1:98400828849:android:e783e87c8718a8c9321190',
    messagingSenderId: '98400828849',
    projectId: 'my-note-90e33',
    databaseURL: 'https://my-note-90e33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-note-90e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUq3Pj3lIjP5S01DGwgLaZE1EZ2-LnD5o',
    appId: '1:98400828849:ios:a4d40306910ae410321190',
    messagingSenderId: '98400828849',
    projectId: 'my-note-90e33',
    databaseURL: 'https://my-note-90e33-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'my-note-90e33.appspot.com',
    iosClientId: '98400828849-g2pe58k1rbnr3t85jl21t6s0pal2pnab.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
